# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "LaTeX.css"
license = "MIT"
licenselink = "https://github.com/PonderCodes/hugo-latex-css/blob/main/LICENSE"
description = "An implementation of LaTeX.css for Hugo"
homepage = "https://latex-css.ponder.codes/"
tags = ["latex"]
features = []
min_version = "0.41.0"

[author]
  name = "Ponder"
  homepage = "https://ponder.codes"

# If porting an existing theme
[original]
  name = "LaTeX.css"
  homepage = "https://latex.vercel.app/"
  repo = "https://github.com/vincentdoerig/latex-css"
